### ISSUE TITLE
Question about certain lines of code

### ISSUE THREAD

**Issue by hello1910** [nwojke/cosine_metric_learning#12]
Thanks so much for such an excellent repository! I have a question about the code, if that's alright.

In your good_mask in market1501.py, where do you set (i,j) to zero if i is a query image and j is a gallery image that starts with -1? You set the junk images in junk_mat to equal zero, but aren't there other junk images that start with -1 that aren't in junk_mat?

Thanks so much!

**Comment by nwojke** [comment]
Are you talking about [this function](https://github.com/nwojke/cosine_metric_learning/blob/master/datasets/market1501.py#L108)? If so, the junk_mat is read from a matlab file.

Note that we never actually used anything other than the image filenames from that function since evaluation has been carried out with the official evaluation toolkit (I am quite confident that I have tested it, though.. but its worth double checking it).

**Comment by nwojke** [comment]
Closing this one due to inactivity.
